# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets:
      - localhost:9090

  - job_name: 'docker'
         # metrics_path defaults to '/metrics'
         # scheme defaults to 'http'.
    static_configs:
            #      - targets: ['ip-10-0-1-205.ec2.internal:9323']
    - targets:
      - 172.17.0.1:9323

  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: 
        secret_key: 
        port: 9100

